# .github/workflows/gcp-cloud-function.yml
name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main  # Trigger deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      # Deploy Cloud Function
      - name: Deploy function to GCP
        run: |
          gcloud functions deploy my-cloud-function \
            --runtime nodejs16 \
            --trigger-http \
            --allow-unauthenticated \
            --entry-point myFunction \
            --region ${{ secrets.GCP_REGION }}
