name: Deploy to Google Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: SSH into Google Compute Engine instance and deploy
      run: |
        gcloud compute ssh ${{ secrets.GCE_INSTANCE_NAME }} \
          --project ${{ secrets.GCP_PROJECT_ID }} \
          --zone ${{ secrets.GCE_ZONE }} \
          --command "cd /path/to/your/app && git pull && ./deploy.sh"
